/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef VertexUpdate_H
#define VertexUpdate_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "graphps_types.h"

namespace graphps {

#ifdef _WIN32
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class VertexUpdateIf {
 public:
  virtual ~VertexUpdateIf() {}
  virtual void ping() = 0;
};

class VertexUpdateIfFactory {
 public:
  typedef VertexUpdateIf Handler;

  virtual ~VertexUpdateIfFactory() {}

  virtual VertexUpdateIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(VertexUpdateIf* /* handler */) = 0;
};

class VertexUpdateIfSingletonFactory : virtual public VertexUpdateIfFactory {
 public:
  VertexUpdateIfSingletonFactory(const boost::shared_ptr<VertexUpdateIf>& iface) : iface_(iface) {}
  virtual ~VertexUpdateIfSingletonFactory() {}

  virtual VertexUpdateIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(VertexUpdateIf* /* handler */) {}

 protected:
  boost::shared_ptr<VertexUpdateIf> iface_;
};

class VertexUpdateNull : virtual public VertexUpdateIf {
 public:
  virtual ~VertexUpdateNull() {}
  void ping() {
    return;
  }
};


class VertexUpdate_ping_args {
 public:

  VertexUpdate_ping_args(const VertexUpdate_ping_args&);
  VertexUpdate_ping_args& operator=(const VertexUpdate_ping_args&);
  VertexUpdate_ping_args() {
  }

  virtual ~VertexUpdate_ping_args() throw();

  bool operator == (const VertexUpdate_ping_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const VertexUpdate_ping_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const VertexUpdate_ping_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class VertexUpdate_ping_pargs {
 public:


  virtual ~VertexUpdate_ping_pargs() throw();

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class VertexUpdate_ping_result {
 public:

  VertexUpdate_ping_result(const VertexUpdate_ping_result&);
  VertexUpdate_ping_result& operator=(const VertexUpdate_ping_result&);
  VertexUpdate_ping_result() {
  }

  virtual ~VertexUpdate_ping_result() throw();

  bool operator == (const VertexUpdate_ping_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const VertexUpdate_ping_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const VertexUpdate_ping_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class VertexUpdate_ping_presult {
 public:


  virtual ~VertexUpdate_ping_presult() throw();

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class VertexUpdateClient : virtual public VertexUpdateIf {
 public:
  VertexUpdateClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  VertexUpdateClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping();
  void send_ping();
  void recv_ping();
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class VertexUpdateProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<VertexUpdateIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (VertexUpdateProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_ping(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  VertexUpdateProcessor(boost::shared_ptr<VertexUpdateIf> iface) :
    iface_(iface) {
    processMap_["ping"] = &VertexUpdateProcessor::process_ping;
  }

  virtual ~VertexUpdateProcessor() {}
};

class VertexUpdateProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  VertexUpdateProcessorFactory(const ::boost::shared_ptr< VertexUpdateIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< VertexUpdateIfFactory > handlerFactory_;
};

class VertexUpdateMultiface : virtual public VertexUpdateIf {
 public:
  VertexUpdateMultiface(std::vector<boost::shared_ptr<VertexUpdateIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~VertexUpdateMultiface() {}
 protected:
  std::vector<boost::shared_ptr<VertexUpdateIf> > ifaces_;
  VertexUpdateMultiface() {}
  void add(boost::shared_ptr<VertexUpdateIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void ping() {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->ping();
    }
    ifaces_[i]->ping();
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class VertexUpdateConcurrentClient : virtual public VertexUpdateIf {
 public:
  VertexUpdateConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  VertexUpdateConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping();
  int32_t send_ping();
  void recv_ping(const int32_t seqid);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _WIN32
  #pragma warning( pop )
#endif

} // namespace

#endif
